
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 21 23:44:16 CET 2014
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAM = 2;
  public static final int IDENT = 15;
  public static final int ZAREZ = 8;
  public static final int O_ZAG = 6;
  public static final int Z_ZAG = 7;
  public static final int NUMBER = 14;
  public static final int VOID = 13;
  public static final int PLUS = 11;
  public static final int EOF = 0;
  public static final int Z_VIT_ZAG = 4;
  public static final int JEDNAKO = 12;
  public static final int error = 1;
  public static final int PRINT = 9;
  public static final int TACKA_ZAREZ = 5;
  public static final int RETURN = 10;
  public static final int O_VIT_ZAG = 3;
}

