
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 01 16:15:22 CET 2015
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 19;
  public static final int PROCENAT = 43;
  public static final int CONST = 18;
  public static final int ZAREZ = 8;
  public static final int MINUS_MINUS = 32;
  public static final int I = 30;
  public static final int MINUS = 33;
  public static final int STR_CONST = 21;
  public static final int Z_VIT_ZAG = 4;
  public static final int PODELJENO = 42;
  public static final int JEDNAKO = 12;
  public static final int CLASS = 24;
  public static final int PLUS = 11;
  public static final int IF = 16;
  public static final int Z_UGL_ZAG = 23;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int PLUS_PLUS = 31;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int VECE_JEDNAKO = 39;
  public static final int NUMBER = 14;
  public static final int MANJE_JEDNAKO = 40;
  public static final int BREAK = 27;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int O_VIT_ZAG = 3;
  public static final int JEDNAKO_JEDNAKO = 36;
  public static final int UZVICNIK_JEDNAKO = 44;
  public static final int MANJE = 37;
  public static final int ELSE = 17;
  public static final int VECE = 38;
  public static final int READ = 28;
  public static final int O_UGL_ZAG = 22;
  public static final int WHILE = 26;
  public static final int TACKA = 35;
  public static final int EXTENDS = 25;
  public static final int BOOL_CONST = 20;
  public static final int TACKA_ZAREZ = 5;
  public static final int PUTA = 41;
  public static final int PRINT = 9;
  public static final int ILI = 29;
  public static final int Z_ZAG = 7;
  public static final int O_ZAG = 6;
}

